### ISSUE TITLE
Error Messages should be in terms of Lines

### ISSUE THREAD

**Issue by maxsnew** [zydeco-lang/zydeco#19]
Right now the errors use source locations based on character number. It would be preferable to report this in terms of line/column numbers.

In the compilers course I just mapped over the syntax once it was parsed to rewrite the span1s as span2s. Alternatively we could just keep the line information around and change it when we display the error messages (though because this depends on some external state, it might be difficult to use the `Display` trait).

**Comment by maxsnew** [comment]
Fixed in https://github.com/zydeco-lang/zydeco/pull/35?

**Comment by LighghtEeloo** [comment]
Yep : )
