### ISSUE TITLE
StdLib Can't use Builtins

### ISSUE THREAD

**Issue by maxsnew** [zydeco-lang/zydeco#27]
You can define new functions in the stdlib `std.zydeco` but they can't use `extern` functions. For instance if you add
```
pub define double : Thunk(Int -> Ret(Int)) = {
    ! mul 2
};
```
Then `! double 3` will typecheck but the evaluator crashes with
```
Runtime Error: Variable mul not found
```

**Comment by LighghtEeloo** [comment]
Addressed in 36465ef327dac845eba90b1344b332289adfbbe7.

**Comment by maxsnew** [comment]
Ok but if it's fixed then you should add a testcase to demonstrate it.

**Comment by LighghtEeloo** [comment]
I would add a testcase normally but this is our `std.zydeco` and I wasn't sure if adding a almost useless `double` would be the best practice. But thinking about it now, I believe I can add `nand` and `nor` to demonstrate this.

**Comment by maxsnew** [comment]
Well you added `char_eq` which is a very useful stdlib function

**Comment by LighghtEeloo** [comment]
Oh indeed. Though if anyone looks into `char_eq`, that guy will definitely sniff out that something is off :rofl:

**Comment by LighghtEeloo** [comment]
Anyway the patch seems to be in place and doing its job. Maybe we should mark it as completed.
