### ISSUE TITLE
Definitions can't refer to prior definitions

### ISSUE THREAD

**Issue by maxsnew** [zydeco-lang/zydeco#29]
```
define f = { fn (x: Int) -> ret x };
define g = { ! f 0 };
do y <- ! g; ! exit y
```
Expected behavior: Exits with 0 
Actual behavior: `Error: "Unbound variable f (Info: Ann)"`

**Comment by LighghtEeloo** [comment]
Currently only definitions with type annotations will get recognized. I think we can discuss that and reimplement `define` with a better design in mind.

**Comment by LighghtEeloo** [comment]
Should have been resolved by now...
