### ISSUE TITLE
Bidirectional Type Checking

### ISSUE THREAD

**Issue by maxsnew** [zydeco-lang/zydeco#32]
As discussed in #31 , parameterized data and codata types both would be a lot nicer with a bidirectional type system.

Currently, all forms are synthesizing and all variables need annotations when they are introduced. There are a few hacks because of this currently that will be resolved: for instance empty match statements need to be checking forms.

Let's work on this on the branch https://github.com/zydeco-lang/zydeco/tree/parameterized-types.

**Comment by LighghtEeloo** [comment]
Maybe I can take care of this one? Had some ideas for refactoring the type checker for a long time.

**Comment by maxsnew** [comment]
@LighghtEeloo Is there something blocking this getting merged into `main`?

**Comment by LighghtEeloo** [comment]
My poor memory made me overlook the fact that the main branch still exists as the default branch for development. Let's do the merge.
