### ISSUE TITLE
Tutorial Material

### ISSUE THREAD

**Issue by maxsnew** [zydeco-lang/zydeco#33]
We should write some "Intro to Zydeco"/"Intro to Call-by-push-value" material that covers the basics `OS`, `Thunk`, `Ret`, `->`, `data`, `codata`...

**Comment by akaiDing** [comment]
Should we use LaTex?

**Comment by maxsnew** [comment]
No I think we should just write example files with comments and/or markdown files with code examples.

**Comment by akaiDing** [comment]
All right!
