### ISSUE TITLE
Better Type Error Messages

### ISSUE THREAD

**Issue by maxsnew** [zydeco-lang/zydeco#42]
1. The current type error messages are panics, which we should never raise unless there is a bug in zydeco
2. The error messages themselves are not that informative: "thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: KindMismatch { context: "desugaring type application", expected: CType, found: VType }', zydeco-lang/src/zydeco.rs:60:50"

**Comment by LighghtEeloo** [comment]
Oops, wrong reference above. Addressed in f58f62ea789315cdc2979524bd1876e631791347. The trace of type checking is now printed after the error site, and the `unwrap`s are removed.

**Comment by maxsnew** [comment]
Got this message: 
```
Error: In resolve codata, expected type application, but got forall (A : VType) . Thunk(Mo(A)) -> Thunk(A -> Compu) -> Compu
	(cbpv.zy:149:7 - 149:25)
```

What does `in resolve codata` mean? Can we give it a more descriptive message?

**Comment by LighghtEeloo** [comment]
The text after `in ...` is supposed to tell us which process of type-checking we are in. In the current implementation, `resolve_[data/codata]` is the function that handles type applications and type name resolution on nominal data / codata types, given that nominal types have weird equalities and we don't yet have a `fresh` or `abstract` type in the core calculus. Given this cursed implementation, I guess the idea of "letting the user know which part the type checker is working on" doesn't make much sense anymore, at least not in `resolve codata`.

I'm changing the header of the message, i.e. the context, to one of the following:
1. In codata resolution,
2. In (the context of) determining the type of a codata definition that requires some type arguments,

Or, potentially, I can turn the whole sentence around:
"We got <type> during <context> but <structure> is required."

I can also rework on the type checker to support `fresh` type in the core calculus.

**Comment by LighghtEeloo** [comment]
A [quick attempt](https://github.com/zydeco-lang/zydeco/commit/d67aa6edce58c7ed785e7e767b5cd467d67b670e)

**Comment by LighghtEeloo** [comment]
The error messages have been significantly improved. If more specific messages are needed, feel free to open an issue for further adjustments.
