### ISSUE TITLE
Pretty Printing

### ISSUE THREAD

**Issue by maxsnew** [zydeco-lang/zydeco#43]
The type being pretty printed at the end here is not valid code, but it should be:

```
> write_line
{ comatch 
| .arg(s) -> 
  comatch 
  | .arg(k) -> 
    do s <- ! str_append .arg(s) .arg("
") ;
    ! write_str .arg(s) .arg(k)
  end
end } :: Thunk_U(Fn(String(), Fn(Thunk_U(OS()), OS())))
```

I would expect it to print `Thunk(String -> Thunk OS -> OS)`

**Comment by LighghtEeloo** [comment]
Addressed in adfc7f8. Entering values now gives pretty printed types.
