### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by maxsnew** [zydeco-lang/zydeco#50]
We should add a LICENSE. Probably [GPLv3](https://choosealicense.com/licenses/gpl-3.0/) or [MIT](https://choosealicense.com/licenses/mit/). When we do we will need to get everyone who has contributed to the repo to agree to the new license.

**Comment by LighghtEeloo** [comment]
I'm leaning towards MIT because of its simplicity and permissiveness.

**Comment by maxsnew** [comment]
Sounds good to me. Let's do MIT. Just need everyone's consent @SchwarzXia @ricky136973 @akaiDing

**Comment by SchwarzXia** [comment]
Agreed

**Comment by akaiDing** [comment]
Agreed!

**Comment by ricky136973** [comment]
Checked the details of GPLv3 and MIT. MIT looks pretty enough for our project to me. Agreed.

**Comment by LighghtEeloo** [comment]
Great! MIT here we go.
