### ISSUE TITLE
Multiple Files/Modules

### ISSUE THREAD

**Issue by maxsnew** [zydeco-lang/zydeco#6]
To implement a standard library we need to add support for basic namespacing and programming with multi-file programs.

**Comment by akaiDing** [comment]
I'm trying to make this feature like:
When I put this at the beginning of the file
```
import std # for example, import the std.zydeco
```

All the codes in `std.zydeco` will be attached before the current file and can be used in this file.

**Comment by LighghtEeloo** [comment]
More details will be further discussed in #12, #44 and #45.
